CREATE ROLE IF NOT EXISTS analyst;
CREATE ROLE IF NOT EXISTS admin;

GRANT USAGE ON DATABASE CYBERSECURITY_DB TO ROLE analyst;
GRANT USAGE ON SCHEMA CYBERSECURITY_DB.PUBLIC TO ROLE analyst;
GRANT SELECT ON TABLE CYBERSECURITY_DB.PUBLIC.fact_logs TO ROLE analyst;

GRANT ALL PRIVILEGES ON TABLE CYBERSECURITY_DB.PUBLIC.fact_logs TO ROLE admin;

CREATE OR REPLACE MASKING POLICY mask_ip AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ADMIN') THEN val
    ELSE REGEXP_REPLACE(val, '(\\d+\\.\\d+\\.\\d+)\\.\\d+', '\\1.XXX')
  END;

ALTER TABLE fact_logs MODIFY COLUMN source_ip SET MASKING POLICY mask_ip;
ALTER TABLE fact_logs MODIFY COLUMN destination_ip SET MASKING POLICY mask_ip;
